# Databricks notebook source
# COMPUTE: Serverless

# MAGIC %md
# MAGIC # Rural CIN — Infrastructure & Governance Setup
# MAGIC
# MAGIC **What this notebook proves:** Structural data isolation between CIN networks at the Unity Catalog
# MAGIC level. Each network gets its own catalog — not a shared database with row-level filtering,
# MAGIC but a physically separate namespace with IAM-enforced boundaries.
# MAGIC
# MAGIC **The CIN pain point it addresses:** *"If the network sees Network B's data, we're in
# MAGIC big trouble."* The legacy EHR architecture has no network-level isolation. All data lives in
# MAGIC one flat namespace with no audit trail on access boundaries.
# MAGIC
# MAGIC **The defensible business outcome:** Each CIN gets its own catalog. Isolation is enforced
# MAGIC by Unity Catalog permissions, not application code. Provable to an auditor in one SQL query.
# MAGIC
# MAGIC ---
# MAGIC **Synthetic data only — no PHI.** All patient data is generated by
# MAGIC [Synthea](https://synthetichealth.github.io/synthea/) and does not represent real individuals.
# MAGIC
# MAGIC ---
# MAGIC **Prerequisites (complete before running this notebook):**
# MAGIC 1. Install `dbignite` as a workspace library: upload `dbignite-0.2.4-py3-none-any.whl`
# MAGIC    from the repo's `dist/` directory to your workspace libraries, or run once from a terminal:
# MAGIC    ```
# MAGIC    %pip install /Volumes/<catalog>/<schema>/<volume>/dbignite-0.2.4-py3-none-any.whl
# MAGIC    ```
# MAGIC 2. Ensure the current user has `CREATE CATALOG` privilege or a workspace admin has
# MAGIC    pre-created the target catalog.

# COMMAND ----------

# DBTITLE 1,Parameters
dbutils.widgets.text("catalog", "demo_cin_catalog", "CIN Catalog")
# To stamp a second network, change this single parameter:
# dbutils.widgets.text("catalog", "network_b_cin_catalog", "CIN Catalog")  # Network B

catalog = dbutils.widgets.get("catalog")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 1. Create Unity Catalog Resources

# COMMAND ----------

# DBTITLE 1,Catalog + Schemas (Bronze / Silver / Gold)
spark.sql(f"CREATE CATALOG IF NOT EXISTS `{catalog}`")
spark.sql(f"USE CATALOG `{catalog}`")

for schema in ["bronze", "silver", "gold"]:
    spark.sql(f"CREATE SCHEMA IF NOT EXISTS `{catalog}`.`{schema}`")

spark.sql(f"""
CREATE VOLUME IF NOT EXISTS `{catalog}`.`bronze`.`raw_feeds`
COMMENT 'Landing zone for inbound FHIR bundles and ADT feeds from member hospitals'
""")

spark.sql(f"""
CREATE VOLUME IF NOT EXISTS `{catalog}`.`bronze`.`checkpoints`
COMMENT 'Streaming checkpoint storage for DLT and Auto Loader pipelines'
""")

print(f"Catalog `{catalog}` ready with bronze/silver/gold schemas and raw_feeds volume.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 2. Load Synthetic FHIR Data into Volume
# MAGIC
# MAGIC Copy Synthea FHIR bundles from the public S3 dataset into our Volume.
# MAGIC These represent the ADT feeds and clinical data that flow from the multiple member hospitals.

# COMMAND ----------

# DBTITLE 1,Copy Synthea FHIR Bundles to Volume
volume_path = f"/Volumes/{catalog}/bronze/raw_feeds"

# Synthea FHIR R4 bundles — public, no credentials required
synthea_s3 = "s3://hls-eng-data-public/data/synthea/fhir/fhir/"

try:
    existing = dbutils.fs.ls(f"{volume_path}/fhir_bundles/")
    print(f"FHIR bundles already present ({len(existing)} files). Skipping copy.")
except Exception:
    print("Copying Synthea FHIR bundles to Volume (first run only)...")
    dbutils.fs.mkdirs(f"{volume_path}/fhir_bundles/")
    # Copy a representative subset — 50 bundles is sufficient for the demo
    files = dbutils.fs.ls(synthea_s3)[:50]
    for f in files:
        dbutils.fs.cp(f.path, f"{volume_path}/fhir_bundles/{f.name}")
    print(f"Copied {len(files)} FHIR bundles to {volume_path}/fhir_bundles/")

# COMMAND ----------

# DBTITLE 1,Copy ADT Sample Records to Volume
import json

# Copy the ADT records that ship with the repo
adt_source = "s3://hls-eng-data-public/data/synthea/fhir/fhir/"
adt_volume = f"{volume_path}/adt_records/"
dbutils.fs.mkdirs(adt_volume)

# Use a few Synthea bundles as representative ADT feeds
adt_files = dbutils.fs.ls(f"{volume_path}/fhir_bundles/")[:4]
for f in adt_files:
    dbutils.fs.cp(f.path, f"{adt_volume}{f.name}")
print(f"Staged {len(adt_files)} ADT records in {adt_volume}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 3. Generate Malformed ADT Message
# MAGIC
# MAGIC This is the quarantine trigger for Notebook 01. A FHIR bundle where the Patient
# MAGIC resource is missing its `id` field — the kind of silent data corruption that the legacy EHR
# MAGIC currently drops without a trace.

# COMMAND ----------

# DBTITLE 1,Create Deliberately Malformed ADT Bundle
malformed_bundle = {
    "resourceType": "Bundle",
    "type": "message",
    "id": "malformed-demo-bundle-001",
    "timestamp": "2026-04-15T08:30:00Z",
    "entry": [
        {
            "resource": {
                "resourceType": "MessageHeader",
                "eventCoding": {
                    "system": "http://terminology.hl7.org/CodeSystem/v2-0003",
                    "code": "ADT_A01"
                },
                "source": {"name": "LegacyEHR-Rural-Hospital-7"}
            }
        },
        {
            "resource": {
                "resourceType": "Patient",
                # id is MISSING — this is the defect
                # In the legacy EHR, this record would silently disappear.
                # In this pipeline, it lands in bronze.quarantine_adt.
                "name": [{"given": ["Jane"], "family": "Doe"}],
                "gender": "female",
                "birthDate": "1958-03-12"
            }
        }
    ]
}

malformed_path = f"{volume_path}/adt_records/MALFORMED_NO_PATIENT_ID.json"
dbutils.fs.put(malformed_path, json.dumps(malformed_bundle, indent=2), overwrite=True)
print(f"Malformed ADT bundle written to {malformed_path}")
print("Expected behavior: Notebook 01 quarantines this record on missing patient_id.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 4. Create DLT Pipeline for Bronze Ingest
# MAGIC
# MAGIC The pipeline runs on **DLT Serverless** in **Triggered** mode — it processes new files
# MAGIC when triggered, then shuts down. No idle compute, no grant dollars spent on waiting.

# COMMAND ----------

# DBTITLE 1,Create Bronze ADT Pipeline
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.pipelines import (
    PipelineCluster,
    PipelineLibrary,
    NotebookLibrary,
)

w = WorkspaceClient()

# Resolve the notebook path relative to this notebook
nb_context = json.loads(
    dbutils.notebook.entry_point.getDbutils().notebook().getContext().toJson()
)
notebook_dir = "/".join(nb_context["extraContext"]["notebook_path"].split("/")[:-1])
bronze_notebook = f"{notebook_dir}/01_bronze_ingest_adt"

pipeline_name = f"{catalog}_bronze_adt"

# Check if pipeline already exists
existing_pipelines = [
    p for p in w.pipelines.list_pipelines()
    if p.name == pipeline_name
]

if existing_pipelines:
    pipeline_id = existing_pipelines[0].pipeline_id
    print(f"Pipeline '{pipeline_name}' already exists: {pipeline_id}")
else:
    result = w.pipelines.create(
        name=pipeline_name,
        catalog=catalog,
        target="bronze",
        serverless=True,
        continuous=False,  # Triggered, not continuous — zero idle cost
        libraries=[
            PipelineLibrary(
                notebook=NotebookLibrary(path=bronze_notebook)
            )
        ],
        configuration={
            "raw_feeds_volume": f"/Volumes/{catalog}/bronze/raw_feeds/adt_records/",
        },
    )
    pipeline_id = result.pipeline_id
    print(f"Created pipeline '{pipeline_name}': {pipeline_id}")

# COMMAND ----------

# DBTITLE 1,Trigger Pipeline Run
update = w.pipelines.start_update(pipeline_id=pipeline_id, full_refresh=True)
print(f"Pipeline triggered. Update ID: {update.update_id}")
print(f"Monitor at: #joblist/pipelines/{pipeline_id}")
print("While it runs, open notebook 01_bronze_ingest_adt to walk through the pipeline code.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 5. Unity Catalog Isolation Demo
# MAGIC
# MAGIC The cell below is **commented out** — the demo workspace likely has only one catalog.
# MAGIC Read it aloud during the demo. This is the structural guarantee that makes multi-CIN
# MAGIC safe: isolation at the catalog level, not a WHERE clause.

# COMMAND ----------

# -- Demonstrates structural isolation. Do not run in demo unless asked.
#
# -- Network A analyst can see Network A data:
# GRANT USE CATALOG ON CATALOG demo_cin_catalog TO `network_a_analyst@example-cin.com`;
# GRANT USE SCHEMA ON SCHEMA demo_cin_catalog.gold TO `network_a_analyst@example-cin.com`;
# GRANT SELECT ON SCHEMA demo_cin_catalog.gold TO `network_a_analyst@example-cin.com`;
#
# -- Network B analyst can see Network B data:
# GRANT USE CATALOG ON CATALOG network_b_cin_catalog TO `network_b_analyst@example-cin.com`;
# GRANT USE SCHEMA ON SCHEMA network_b_cin_catalog.gold TO `network_b_analyst@example-cin.com`;
# GRANT SELECT ON SCHEMA network_b_cin_catalog.gold TO `network_b_analyst@example-cin.com`;
#
# -- A network_a_analyst querying network_b_cin_catalog fails at the catalog level,
# -- not a WHERE clause. This is the "if the network sees Network B's data, we're in
# -- big trouble" guarantee. The query doesn't return zero rows — it returns
# -- ACCESS_DENIED before it even parses the table name.

# COMMAND ----------

# MAGIC %md
# MAGIC ## 6. Verify Pipeline Completion
# MAGIC
# MAGIC Wait for the bronze pipeline to finish before proceeding to the silver notebooks.

# COMMAND ----------

# DBTITLE 1,Wait for Pipeline and Query Quarantine
import time

for attempt in range(30):
    state = w.pipelines.get(pipeline_id).state.value
    if state in ("IDLE", "FAILED"):
        break
    print(f"Pipeline state: {state} (waiting...)")
    time.sleep(10)

print(f"Pipeline final state: {state}")

if state == "IDLE":
    print("\n--- Quarantine table (records rejected by quality rules) ---")
    display(spark.sql(f"SELECT * FROM `{catalog}`.`bronze`.`quarantine_adt`"))
else:
    print(f"Pipeline did not complete successfully. Check pipeline UI for details.")

# COMMAND ----------

# MAGIC %md
# MAGIC ---
# MAGIC **What's next:** [01_bronze_ingest_adt](01_bronze_ingest_adt) — walk through the DLT pipeline
# MAGIC code that just ran, then query the quarantine table.
# MAGIC
# MAGIC **Cost footprint:** Catalog/schema creation is free. Volume storage: ~$0.02/GB/month.
# MAGIC Data copy: one-time S3 read (~$0.01). Total setup overhead: <$0.10.
